// <auto-generated />
using System;
using EventTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTracker.Migrations
{
    [DbContext(typeof(EventContext))]
    partial class EventContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("EventTracker.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ilk etkinlik için açıklama.",
                            Title = "Örnek Etkinlik 1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 2, 20, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "ikinci etkinlik için açıklama.",
                            Title = "Örnek Etkinlik 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
